# Generated by Django 5.2.8 on 2025-11-30 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_remove_monthly_test_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dailyusage",
            name="unique_user_date",
        ),
        migrations.RenameIndex(
            model_name="dailyusage",
            new_name="daily_usage_user_id_afd481_idx",
            old_name="daily_usage_user_date_idx",
        ),
        migrations.RenameIndex(
            model_name="dailyusage",
            new_name="daily_usage_date_abe0cf_idx",
            old_name="daily_usage_date_idx",
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_photos_per_day",
            field=models.IntegerField(
                default=3,
                help_text="DEPRECATED: используйте daily_photo_limit. -1 = неограниченно",
                verbose_name="Макс. фото в день (legacy)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyusage",
            unique_together={("user", "date")},
        ),
    ]
