# Generated by Django 6.0 on 2025-12-24 11:22

import apps.billing.usage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_add_queued_status_to_webhook_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyusage",
            name="date",
            field=models.DateField(
                default=apps.billing.usage._get_today, verbose_name="Дата"
            ),
        ),
    ]
