# Generated by Django 5.2.8 on 2025-12-24 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_alter_dailyusage_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="billing_period_end",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Для recurring: end_date подписки на момент создания платежа. Используется для DB guard.",
                null=True,
                verbose_name="Окончание периода оплаты",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["subscription", "billing_period_end", "status"],
                name="payments_subscri_54c43b_idx",
            ),
        ),
    ]
