# Generated by Django 6.0 on 2025-12-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0003_personalplansurvey_personalplan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalplan",
            name="ai_model",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="AI модель"
            ),
        ),
        migrations.AlterField(
            model_name="personalplan",
            name="ai_text",
            field=models.TextField(verbose_name="Текст плана от AI"),
        ),
        migrations.AlterField(
            model_name="personalplan",
            name="prompt_version",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Версия промпта"
            ),
        ),
        migrations.AlterField(
            model_name="personalplan",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_plans",
                to="telegram.personalplansurvey",
                verbose_name="Опрос",
            ),
        ),
        migrations.AlterField(
            model_name="personalplansurvey",
            name="body_goals",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Цели по телу"
            ),
        ),
        migrations.AlterField(
            model_name="personalplansurvey",
            name="body_ideal_file",
            field=models.TextField(verbose_name="Файл идеального типа фигуры"),
        ),
        migrations.AlterField(
            model_name="personalplansurvey",
            name="body_now_file",
            field=models.TextField(verbose_name="Файл текущего типа фигуры"),
        ),
        migrations.AlterField(
            model_name="personalplansurvey",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AlterField(
            model_name="personalplansurvey",
            name="health_limitations",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Ограничения по здоровью"
            ),
        ),
        migrations.AlterField(
            model_name="personalplansurvey",
            name="height_cm",
            field=models.PositiveSmallIntegerField(
                help_text="Рост (120-250)", verbose_name="Рост (см)"
            ),
        ),
        migrations.AlterField(
            model_name="personalplansurvey",
            name="target_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Целевой вес (кг)",
            ),
        ),
        migrations.AlterField(
            model_name="personalplansurvey",
            name="timezone",
            field=models.CharField(
                default="Europe/Moscow",
                help_text="Например, Europe/Moscow",
                max_length=64,
                verbose_name="Часовой пояс",
            ),
        ),
        migrations.AlterField(
            model_name="personalplansurvey",
            name="training_level",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Уровень тренированности",
            ),
        ),
        migrations.AlterField(
            model_name="personalplansurvey",
            name="utc_offset_minutes",
            field=models.IntegerField(verbose_name="Смещение UTC (минуты)"),
        ),
        migrations.AlterField(
            model_name="personalplansurvey",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Вес (кг)"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="recommended_calories",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Рекомендованные калории"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="recommended_carbs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Рекомендованные углеводы (г)",
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="recommended_fat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Рекомендованные жиры (г)",
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="recommended_protein",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Рекомендованные белки (г)",
            ),
        ),
    ]
